#define LIBGPKG_VERSION "0.9.18"

/* #undef TLS_USE_THREAD */
#define TLS_USE_DECLSPEC_THREAD
/* #undef TLS_USE_PTHREAD */

/* #undef GPKG_GEOM_FUNC */

#define HAVE_LOCALE_H
/* #undef HAVE_XLOCALE_H */
#define LOCALE_USE__CREATE_LOCALE
/* #undef LOCALE_USE_NEWLOCALE */
/* #undef LOCALE_USE_SET_LOCALE */
